export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL'

export const LOGOUT = 'LOGOUT'

export const  REGISTER_REQUEST = 'REGISTER_REQUEST'
export const  REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS'
export const  REGISTER_REQUEST_FAIL = 'REGISTER_REQUEST_FAIL'

export const SOCKET_AUTH = 'SOCKET_AUTH'
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE'
export const SOCKET_SUBSCRIBE = 'SOCKET_SUBSCRIBE'


